[package]
name = "config"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
dirs = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
once_cell = { workspace = true }